### ISSUE TITLE
Process breaked on error

### ISSUE THREAD

**Issue by huacnlee** [pkrumins/nodejs-proxy#5]
```
27 Oct 17:28:44 - 221.237.179.232: GET http://img3.cache.netease.com/house/2010/10/27/20101027100318059a4.jpg

node.js:50
    throw e; // process.nextTick error, or 'error' event on first tick
    ^
Error: ETIMEDOUT, Connection timed out
    at IOWatcher.callback (net.js:877:22)
    at node.js:634:9
```

**Comment by pkrumins** [comment]
noted. will fix it some time later. for now you could just wrap it in a try catch to fix this.

**Comment by yadutaf** [comment]
Maybe, a quick fix: add the end of the code, there is a last chance error handler that is commented by default. It is nonetheless recommended to uncomment it in a production environment. Anyway, we still need to automatically activate it in production.

@pkrumins I can handle it if you wish. btw, it's pretty easy :)

**Comment by pkrumins** [comment]
that would be great @jtlebi!
